-- Auto-généré depuis data/catalogue-formations-start-academy.xlsx
-- Ne pas éditer à la main : régénérer via `npm run generate:catalog`.
--
-- Ce seed est idempotent : `supabase db reset` ou un nouvel appel
-- écrasera proprement les modules existants.

insert into public.training_modules (id, name, family, source_sheet, target_profile, duration_hours, level, tools, paying, platform, need_identification, is_foundation_module, diagnostic_signals) values
  (
    'conseiller-base-param-trages-fonctionnalit-s-chat-gpt',
    'Chat gpt',
    'Base (paramétrages fonctionnalités)',
    'Conseiller',
    'conseiller',
    4.0,
    0.0,
    null,
    null,
    null,
    'L''équipe a-t-elle déjà paramétré ChatGPT : instructions personnalisées, mémoire/projets, GPTs utiles, règles de confidentialité, modèles de prompts ? Les conseillers savent-ils l''utiliser sur des cas métier concrets : préparation RDV vendeur, compte rendu, relance, objection, analyse de stats ? Mesure-t-on le gain : temps gagné, relances envoyées, qualité des réponses, taux RDV ?',
    true,
    ARRAY['Équipe junior', 'Compétence — Écarts forts entre conseillers ou dépendance au manager', 'IA utile — IA utilisée sans indicateur de gain ou sans adoption terrain', 'Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'ChatGPT - paramétrage — Chaque conseiller utilise l''outil différemment ; résultats inégaux ; peur de l''erreur ou de la confidentialité.']::text[]
  ),
  (
    'conseiller-base-param-trages-fonctionnalit-s-gamma',
    'Gamma',
    'Base (paramétrages fonctionnalités)',
    'Conseiller',
    'conseiller',
    2.0,
    0.0,
    null,
    null,
    null,
    'Les conseillers ont-ils déjà réalisé une présentation sur Gamma ? Savent-ils transformer un diagnostic vendeur, un bilan de diffusion ou une proposition de service en support clair, à la charte, utilisable en RDV ? Le frein est-il l''outil, la structure du message, le design ou le temps de production ?',
    true,
    ARRAY['Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'Supports commerciaux faibles — Les conseillers savent-ils produire une présentation propre et orientée décision ?', 'Gamma — Supports moches, trop longs, faits à la dernière minute. Grande tradition locale.']::text[]
  ),
  (
    'conseiller-base-param-trages-fonctionnalit-s-notebook-lm',
    'Notebook LM',
    'Base (paramétrages fonctionnalités)',
    'Conseiller',
    'conseiller',
    4.0,
    0.0,
    null,
    null,
    null,
    'Connaissent-ils NotebookLM et savent-ils s''en servir avec des sources fiables : diagnostics, PV d''AG, règlement de copropriété, offres, documents agence, supports formation ? Savent-ils obtenir une synthèse exploitable sans inventer ? Le besoin porte-t-il sur fiabilité, rapidité de lecture ou vulgarisation client ?',
    true,
    ARRAY['Documents mal exploités — NotebookLM ou autre outil documentaire est-il connu et maîtrisé ?', 'NotebookLM — Lecture longue, erreurs d''interprétation, dépendance au manager pour synthétiser.']::text[]
  ),
  (
    'conseiller-base-param-trages-fonctionnalit-s-claude',
    'Claude',
    'Base (paramétrages fonctionnalités)',
    'Conseiller',
    'conseiller',
    4.0,
    0.0,
    null,
    null,
    null,
    'Ont-ils déjà testé Claude pour produire des contenus longs et structurés : supports, scripts, mails, comptes rendus, déroulés, matrices ? Savent-ils comparer les usages avec ChatGPT ? Le besoin est-il de produire plus vite, de mieux structurer ou de standardiser les livrables de l''équipe ?',
    true,
    ARRAY['Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'Claude — Documents hétérogènes, trames inexistantes, qualité dépendante de la personne.']::text[]
  ),
  (
    'conseiller-base-param-trages-fonctionnalit-s-gemini',
    'Gemini',
    'Base (paramétrages fonctionnalités)',
    'Conseiller',
    'conseiller',
    2.0,
    0.0,
    null,
    null,
    null,
    'L''équipe utilise-t-elle Google Workspace et Gemini : Gmail, Drive, Docs, Sheets, Slides ? Les conseillers savent-ils rechercher, synthétiser et rédiger à partir de leurs documents ? Où se perd le plus de temps : retrouver l''information, produire un document, partager, suivre ou relancer ?',
    true,
    ARRAY['Gemini / Google Workspace — Infos dispersées, doublons, documents introuvables, relances oubliées.']::text[]
  ),
  (
    'conseiller-base-param-trages-fonctionnalit-s-prompt',
    'Prompt',
    'Base (paramétrages fonctionnalités)',
    'Conseiller',
    'conseiller',
    1.0,
    0.0,
    'prompt creator',
    null,
    null,
    'Les conseillers savent-ils écrire un prompt métier réutilisable avec contexte, rôle, objectif, contraintes, données d''entrée et format de sortie ? Ont-ils une bibliothèque commune de prompts ? Les résultats produits sont-ils exploitables du premier coup ou faut-il tout refaire, comme souvent quand l''humain appelle ça ''tester'' ?',
    true,
    ARRAY['Équipe junior', 'Compétence — Écarts forts entre conseillers ou dépendance au manager', 'IA utile — IA utilisée sans indicateur de gain ou sans adoption terrain', 'Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'ChatGPT - paramétrage — Chaque conseiller utilise l''outil différemment ; résultats inégaux ; peur de l''erreur ou de la confidentialité.', 'Méthode de prompt — L''IA est jugée mauvaise alors que la demande est vide. Scénario classique.']::text[]
  ),
  (
    'conseiller-prospection-usecases-secteur-base-de-donn-es',
    'Secteur base de données',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    'My boitage',
    false,
    'Gpt',
    'Les conseillers connaissent-ils leurs secteurs prioritaires et leurs volumes de prospection ? Combien de contacts propriétaires qualifiés créent-ils par semaine ? Le frein vient-il du ciblage, de la base de données, de la régularité ou du suivi ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-prospection-usecases-g-n-ration-de-contenu',
    'Génération de contenu',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    2.0,
    2.0,
    'Prospect IA',
    false,
    null,
    'Les contenus générés produisent-ils des contacts ou seulement de la visibilité ? Quels ratios suivez-vous : publications, messages envoyés, réponses, RDV pris ? Les conseillers savent-ils adapter le contenu à la cible, au canal et à l''objectif commercial ?',
    false,
    ARRAY['Manque de mandats / peu de vendeurs / faible prospection', 'Beaucoup de vues mais peu de contacts', 'Prospection — Pas de chiffre connu, moins de 10 contacts qualifiés, ou prospection irrégulière']::text[]
  ),
  (
    'conseiller-prospection-usecases-expert-dpe',
    'Expert DPE',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    2.0,
    2.0,
    'A créer via gpt',
    false,
    null,
    'Les conseillers maîtrisent-ils l''impact du DPE sur le prix, le délai de vente et l''argumentaire vendeur ? Combien de RDV ou mandats sont perdus faute d''explication claire ? Le besoin est-il technique, commercial ou pédagogique ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-prospection-usecases-base-de-donn-es-entretien-relance',
    'Base de données entretien relance',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    2.0,
    3.0,
    'A créer agent',
    true,
    null,
    'Combien de contacts dormants sont relancés chaque semaine par conseiller ? Quel taux de réponse et de RDV obtenez-vous ? Le problème vient-il de la discipline de relance, de la qualité du message ou de l''absence d''automatisation ?',
    false,
    ARRAY['Base acquéreurs ou vendeurs dormante', 'CRM mal utilisé — Le problème vient-il de l''outil, de la discipline ou du process ?']::text[]
  ),
  (
    'conseiller-prospection-usecases-estimation-barom-tre',
    'Estimation baromètre',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    1.0,
    2.0,
    'A créer',
    false,
    null,
    'Les conseillers savent-ils utiliser les données marché pour renforcer une estimation ? Le taux estimation -> mandat est-il insuffisant ? Le besoin est-il de mieux préparer le RDV, de mieux argumenter le prix ou de rendre la donnée compréhensible pour le vendeur ?',
    false,
    ARRAY['Estimations nombreuses mais peu de mandats', 'Estimation — Taux faible ou très variable entre conseillers']::text[]
  ),
  (
    'conseiller-prospection-usecases-pige-faq',
    'Pige Faq',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    2.0,
    2.0,
    'Vendre seul bien accompagné',
    false,
    null,
    'Quel est le taux appels PAP -> conversations -> RDV -> mandats ? Les conseillers savent-ils traiter les objections et créer de la valeur face au ''je vends seul'' ? Le besoin porte-t-il sur script, posture, relance ou preuve de valeur ?',
    false,
    ARRAY['Manque de mandats / peu de vendeurs / faible prospection', 'Prospection — Pas de chiffre connu, moins de 10 contacts qualifiés, ou prospection irrégulière', 'RDV vendeur — Beaucoup d’actions mais peu de RDV : problème de ciblage, message ou posture', 'Pige / veille annonces — Peu de RDV PAP, relances non suivies, faible argumentaire face au vendeur.']::text[]
  ),
  (
    'conseiller-prospection-usecases-e-r-putation',
    'e réputation',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    'A créer',
    false,
    null,
    'Les avis clients sont-ils demandés systématiquement au bon moment ? Combien d''avis récents par conseiller ou par agence ? Le besoin est-il d''améliorer la crédibilité commerciale, la méthode de demande ou le suivi des clients satisfaits ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-prospection-usecases-veille-concurrentielle',
    'Veille concurrentielle',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    2.0,
    1.0,
    'A créer',
    false,
    null,
    'Les conseillers analysent-ils les biens concurrents avant estimation, suivi vendeur et négociation ? Utilisent-ils cette veille pour améliorer le taux de mandat, la baisse de prix ou l''acceptation d''offre ? Le besoin est-il méthode, outil ou discipline ?',
    false,
    ARRAY['Estimations nombreuses mais peu de mandats', 'Vendeurs difficiles à faire baisser', 'Équipe confirmée mais irrégulière', 'Estimation — Taux faible ou très variable entre conseillers', 'Suivi vendeur — Suivi irrégulier, vendeur surpris, baisses tardives', 'Négociation — Offres transmises mais non travaillées', 'Pige / veille annonces — Peu de RDV PAP, relances non suivies, faible argumentaire face au vendeur.']::text[]
  ),
  (
    'conseiller-prospection-usecases-r-seaux-sociaux',
    'Réseaux sociaux',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    2.0,
    2.0,
    'rien',
    true,
    'claude design',
    'Les réseaux sociaux contribuent-ils réellement aux objectifs commerciaux : notoriété locale, contacts vendeurs, recrutement acquéreurs, preuve d''expertise ? Quels ratios sont suivis : messages entrants, RDV, mandats ? Le besoin est-il contenu, régularité ou conversion ?',
    false,
    ARRAY['Beaucoup de vues mais peu de contacts', 'RDV vendeur — Beaucoup d’actions mais peu de RDV : problème de ciblage, message ou posture', 'Réseaux sociaux — Posts sans cible, sans appel à l''action, sans mesure.']::text[]
  ),
  (
    'conseiller-prospection-usecases-entrainement',
    'Entrainement',
    'Prospection (usecases)',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    'Train my agent',
    true,
    null,
    'Les conseillers s''entraînent-ils sur les situations qui font perdre du chiffre : appel PAP, objection commission, exclusivité, baisse de prix, offre basse ? Mesure-t-on leur progression ? Le besoin est-il de renforcer compétence, posture ou réflexes terrain ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-vendeur-suivi',
    'Suivi',
    'Vendeur',
    'Conseiller',
    'conseiller',
    2.0,
    1.0,
    'Projet',
    false,
    null,
    'À quelle fréquence les vendeurs reçoivent-ils un compte rendu utile ? Le suivi améliore-t-il le taux de baisse de prix, de maintien mandat et de satisfaction client ? Le besoin est-il régularité, analyse ou capacité à dire les choses clairement ?',
    false,
    ARRAY['Vendeurs difficiles à faire baisser', 'Beaucoup de visites mais peu d’offres', 'Base acquéreurs ou vendeurs dormante', 'Équipe confirmée mais irrégulière', 'Suivi vendeur — Suivi irrégulier, vendeur surpris, baisses tardives', 'Diffusion — Beaucoup de vues mais peu de clics : annonce/photos. Beaucoup de visites mais peu d’offres : prix ou qualification', 'Acheteur — Visites nombreuses sans offre : découverte faible, mauvais matching ou prix mal traité', 'Négociation — Offres transmises mais non travaillées']::text[]
  ),
  (
    'conseiller-vendeur-suivi-automatis',
    'Suivi automatisé',
    'Vendeur',
    'Conseiller',
    'conseiller',
    4.0,
    3.0,
    'Agent',
    true,
    'gpt',
    'Combien de temps est perdu chaque semaine sur les comptes rendus vendeurs ? Les relances sont-elles faites dans les délais ? L''automatisation doit-elle améliorer le ratio temps passé / qualité perçue / décisions obtenues ?',
    false,
    ARRAY['Vendeurs difficiles à faire baisser', 'Suivi vendeur — Suivi irrégulier, vendeur surpris, baisses tardives']::text[]
  ),
  (
    'conseiller-vendeur-chatbot-mandat',
    'Chatbot mandat',
    'Vendeur',
    'Conseiller',
    'conseiller',
    2.0,
    1.0,
    null,
    false,
    'Notebook',
    'Les conseillers comprennent-ils suffisamment le mandat pour le présenter sans approximation ? Quelles erreurs ou hésitations apparaissent en RDV ? Le besoin est-il juridique de premier niveau, argumentaire ou sécurisation de la signature ?',
    false,
    ARRAY['Mandats simples mais peu d’exclusivités']::text[]
  ),
  (
    'conseiller-vendeur-production-esti-autre-langue-et-vid-o',
    'Production esti autre langue et vidéo',
    'Vendeur',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    null,
    false,
    'Notebook',
    'Avez-vous des vendeurs étrangers, éloignés ou peu disponibles ? Les conseillers savent-ils produire une restitution claire, multilingue ou vidéo ? Le besoin est-il d''améliorer la compréhension client, la réactivité ou l''image professionnelle ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-vendeur-d-couverte-et-remerciements',
    'Découverte et remerciements',
    'Vendeur',
    'Conseiller',
    'conseiller',
    2.0,
    1.0,
    'protocole vendeur',
    false,
    'gpt',
    'Après un RDV vendeur, les conseillers font-ils systématiquement une synthèse et une relance ? Quel taux de second RDV ou de mandat est obtenu après cette relance ? Le besoin est-il méthode de suivi, qualité du message ou rythme commercial ?',
    false,
    ARRAY['Équipe junior']::text[]
  ),
  (
    'conseiller-vendeur-veille-concurrentielle',
    'Veille concurrentielle',
    'Vendeur',
    'Conseiller',
    'conseiller',
    2.0,
    1.0,
    null,
    false,
    'notebook',
    'Avant un RDV vendeur, les conseillers savent-ils comparer le bien aux concurrents directs ? Cette analyse aide-t-elle à obtenir le bon prix ou l''exclusivité ? Le besoin est-il de créer un réflexe d''analyse marché avant chaque rendez-vous ?',
    false,
    ARRAY['Estimations nombreuses mais peu de mandats', 'Vendeurs difficiles à faire baisser', 'Équipe confirmée mais irrégulière', 'Estimation — Taux faible ou très variable entre conseillers', 'Suivi vendeur — Suivi irrégulier, vendeur surpris, baisses tardives', 'Négociation — Offres transmises mais non travaillées', 'Pige / veille annonces — Peu de RDV PAP, relances non suivies, faible argumentaire face au vendeur.']::text[]
  ),
  (
    'conseiller-vendeur-entrainement',
    'Entrainement',
    'Vendeur',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    'Train my agent',
    false,
    null,
    'Les conseillers sont-ils capables de conduire un RDV vendeur complet sans perdre le fil : découverte, estimation, exclusivité, objections, conclusion ? Sur quels passages perdent-ils le plus de performance ? Le besoin est-il entraînement, script ou feedback ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-vendeur-annonces',
    'Annonces',
    'Vendeur',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    null,
    false,
    null,
    'Les annonces génèrent-elles assez de clics, contacts et visites par rapport aux vues ? Les conseillers savent-ils identifier si le problème vient du prix, du titre, des photos, du texte ou du positionnement ? Le besoin est-il rédaction, analyse ou optimisation ?',
    false,
    ARRAY['Beaucoup de vues mais peu de contacts', 'Diffusion — Beaucoup de vues mais peu de clics : annonce/photos. Beaucoup de visites mais peu d’offres : prix ou qualification']::text[]
  ),
  (
    'conseiller-vendeur-photos',
    'Photos',
    'Vendeur',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    null,
    false,
    null,
    'Les photos actuelles améliorent-elles l''attractivité des biens ? Les conseillers savent-ils préparer un logement, sélectionner les visuels et détecter les photos qui pénalisent le taux de clic ? Le besoin est-il technique, commercial ou process ?',
    false,
    ARRAY['Beaucoup de vues mais peu de contacts', 'Diffusion — Beaucoup de vues mais peu de clics : annonce/photos. Beaucoup de visites mais peu d’offres : prix ou qualification']::text[]
  ),
  (
    'conseiller-vendeur-vid-os',
    'Vidéos',
    'Vendeur',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    null,
    true,
    null,
    'La vidéo est-elle utilisée pour augmenter la confiance, la projection ou le suivi vendeur ? Mesurez-vous son impact sur les contacts, visites qualifiées ou mandats ? Le besoin est-il tournage, scénario, diffusion ou présentation client ?',
    false,
    ARRAY['Diffusion — Beaucoup de vues mais peu de clics : annonce/photos. Beaucoup de visites mais peu d’offres : prix ou qualification']::text[]
  ),
  (
    'conseiller-vendeur-pr-paration-r1',
    'Préparation R1',
    'Vendeur',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    null,
    false,
    null,
    'Les R1 vendeurs sont-ils préparés avec des objectifs clairs : découverte, motivation, concurrence, délai, prix, décisionnaire ? Quel taux R1 -> R2 obtenez-vous ? Le besoin est-il trame, qualification ou posture de découverte ?',
    false,
    ARRAY['Équipe junior']::text[]
  ),
  (
    'conseiller-vendeur-pr-pa-r2',
    'Prépa R2',
    'Vendeur',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    null,
    false,
    null,
    'Les R2 aboutissent-ils à une décision claire ? Quel taux R2 -> mandat signé et mandat exclusif ? Les conseillers savent-ils défendre leur estimation, présenter la stratégie et conclure ? Le besoin est-il argumentaire, preuve de valeur ou conclusion ?',
    false,
    ARRAY['Estimations nombreuses mais peu de mandats', 'Mandats simples mais peu d’exclusivités', 'Estimation — Taux faible ou très variable entre conseillers', 'Exclusivité — Exclusivité rarement proposée ou mal défendue']::text[]
  ),
  (
    'conseiller-vendeur-plan-de-comm-vendeur',
    'Plan de comm vendeur',
    'Vendeur',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    null,
    false,
    null,
    'Le plan de communication aide-t-il réellement à signer le mandat ou reste-t-il une liste d''actions standard ? Les vendeurs comprennent-ils ce qui différencie l''agence ? Le besoin est-il packaging, discours commercial ou preuve de suivi ?',
    false,
    ARRAY['Mandats simples mais peu d’exclusivités', 'Exclusivité — Exclusivité rarement proposée ou mal défendue']::text[]
  ),
  (
    'conseiller-vendeur-dossier-r-nov',
    'Dossier rénov',
    'Vendeur',
    'Conseiller',
    'conseiller',
    2.0,
    2.0,
    'my renov immo',
    false,
    null,
    'Les conseillers savent-ils évaluer l''impact des travaux sur le prix, la négociation et la projection acquéreur ? Perd-on des visites ou des offres faute de chiffrage ou de solution ? Le besoin est-il conseil vendeur, argumentaire ou support rénov ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-acheteur-d-couverte-et-remerciements-acheteur',
    'Découverte et remerciements acheteur',
    'Acheteur',
    'Conseiller',
    'conseiller',
    2.0,
    1.0,
    null,
    null,
    null,
    'Les acquéreurs sont-ils qualifiés avant visite : financement, urgence, critères, arbitrages, décisionnaires ? Quel taux découverte -> visite et visite -> offre ? Le besoin est-il méthode de découverte, relance ou qualité de synthèse ?',
    false,
    ARRAY['Équipe junior']::text[]
  ),
  (
    'conseiller-acheteur-suivi-acheteur',
    'Suivi acheteur',
    'Acheteur',
    'Conseiller',
    'conseiller',
    2.0,
    1.0,
    null,
    null,
    null,
    'Combien d''acquéreurs qualifiés sont suivis chaque semaine ? Quel taux de relance aboutit à une visite ou une offre ? Le problème vient-il de l''organisation, de la personnalisation ou de l''absence de priorisation ?',
    false,
    ARRAY['Vendeurs difficiles à faire baisser', 'Beaucoup de visites mais peu d’offres', 'Base acquéreurs ou vendeurs dormante', 'Suivi vendeur — Suivi irrégulier, vendeur surpris, baisses tardives', 'Acheteur — Visites nombreuses sans offre : découverte faible, mauvais matching ou prix mal traité']::text[]
  ),
  (
    'conseiller-acheteur-suivi-acheteur-autonome',
    'Suivi acheteur autonome',
    'Acheteur',
    'Conseiller',
    'conseiller',
    4.0,
    3.0,
    null,
    null,
    null,
    'Le suivi acquéreur est-il régulier sans dépendre uniquement de la mémoire du conseiller, cette technologie fragile ? Quels gains attendez-vous : plus de visites, moins d''oublis, meilleure qualification, relances plus rapides ?',
    false,
    ARRAY['Vendeurs difficiles à faire baisser', 'Beaucoup de visites mais peu d’offres', 'Base acquéreurs ou vendeurs dormante', 'Suivi vendeur — Suivi irrégulier, vendeur surpris, baisses tardives', 'Acheteur — Visites nombreuses sans offre : découverte faible, mauvais matching ou prix mal traité']::text[]
  ),
  (
    'conseiller-acheteur-agent-recherche',
    'Agent recherche',
    'Acheteur',
    'Conseiller',
    'conseiller',
    2.0,
    3.0,
    'Agent LBC',
    null,
    'GPT',
    'Les conseillers perdent-ils du temps à chercher des biens au lieu de vendre ? Quel délai entre la demande acquéreur et la proposition de biens ? Le besoin est-il sourcing, matching, qualification ou automatisation de recherche ?',
    false,
    ARRAY['IA utile — IA utilisée sans indicateur de gain ou sans adoption terrain']::text[]
  ),
  (
    'conseiller-acheteur-synth-tiser-pv',
    'Synthétiser pv',
    'Acheteur',
    'Conseiller',
    'conseiller',
    1.0,
    2.0,
    null,
    null,
    'Notebook LM',
    'Les conseillers savent-ils résumer un PV d''AG et détecter les points qui peuvent bloquer une offre ? Combien de ventes ralentissent à cause d''une mauvaise explication copropriété ? Le besoin est-il compétence documentaire ou support de synthèse ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-acheteur-synth-tiser-diags',
    'Synthétiser diags',
    'Acheteur',
    'Conseiller',
    'conseiller',
    1.0,
    2.0,
    null,
    null,
    'Notebook LM',
    'Les diagnostics sont-ils lus avant la visite et l''offre ? Les conseillers savent-ils expliquer les anomalies sans affoler ni minimiser ? Le besoin est-il compréhension technique, discours client ou sécurisation de la négociation ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-acheteur-synth-tiser-copro',
    'Synthétiser copro',
    'Acheteur',
    'Conseiller',
    'conseiller',
    1.0,
    2.0,
    null,
    null,
    'Notebook LM',
    'Les éléments de copropriété sont-ils maîtrisés avant engagement acquéreur ? Les conseillers savent-ils repérer charges, travaux, procédures, fonds travaux ? Le besoin est-il lecture documentaire, synthèse ou explication pédagogique ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-acheteur-synth-tiser-couts-financiers',
    'Synthétiser couts financiers',
    'Acheteur',
    'Conseiller',
    'conseiller',
    1.0,
    2.0,
    null,
    null,
    'Notebook LM',
    'Les conseillers savent-ils expliquer le coût total d''acquisition : frais, charges, travaux, financement, fiscalité simple ? Les offres échouent-elles à cause d''un budget mal cadré ? Le besoin est-il qualification financière ou support de décision ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-admin-synth-tiser-pv',
    'Synthétiser pv',
    'Admin',
    'Conseiller',
    'conseiller',
    1.0,
    2.0,
    null,
    null,
    'Notebook LM',
    'L''équipe sait-elle extraire rapidement les décisions importantes d''un PV ? Le retard de lecture impacte-t-il les délais de vente ou la qualité de conseil ? Le besoin est-il méthode, synthèse ou contrôle des risques ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-admin-synth-tiser-diags',
    'Synthétiser diags',
    'Admin',
    'Conseiller',
    'conseiller',
    1.0,
    2.0,
    null,
    null,
    'Notebook LM',
    'Les diagnostics sont-ils exploités comme un outil de conseil ou seulement rangés dans le dossier, ce grand cimetière numérique ? Le besoin est-il de gagner en compréhension, en anticipation des objections ou en sécurité commerciale ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-admin-synth-tiser-copro',
    'Synthétiser copro',
    'Admin',
    'Conseiller',
    'conseiller',
    1.0,
    2.0,
    null,
    null,
    'Notebook LM',
    'Les informations de copropriété sont-elles fiables, partagées et compréhensibles par tous ? Où apparaissent les erreurs : annonce, visite, offre, compromis ? Le besoin est-il process admin, lecture ou restitution client ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-admin-synth-tiser-couts-financiers',
    'Synthétiser couts financiers',
    'Admin',
    'Conseiller',
    'conseiller',
    1.0,
    2.0,
    null,
    null,
    'Notebook LM',
    'Les coûts financiers et annexes sont-ils présentés de manière homogène ? Les conseillers savent-ils éviter les mauvaises surprises qui cassent une offre ? Le besoin est-il outil de calcul, pédagogie ou contrôle avant engagement ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-admin-annonces',
    'Annonces',
    'Admin',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    null,
    false,
    null,
    'Combien de temps faut-il pour produire une annonce complète ? Les annonces performent-elles selon les ratios vues -> clics -> contacts ? Le besoin est-il rapidité, qualité rédactionnelle, conformité ou adaptation au canal ?',
    false,
    ARRAY['Beaucoup de vues mais peu de contacts', 'Diffusion — Beaucoup de vues mais peu de clics : annonce/photos. Beaucoup de visites mais peu d’offres : prix ou qualification']::text[]
  ),
  (
    'conseiller-admin-chatbot-mandat',
    'Chatbot mandat',
    'Admin',
    'Conseiller',
    'conseiller',
    2.0,
    1.0,
    null,
    false,
    'Notebook',
    'Les clients posent-ils souvent les mêmes questions sur le mandat ? Les conseillers répondent-ils de façon homogène et sécurisée ? Le besoin est-il d''améliorer la compétence mandat ou de fournir un support d''aide à la réponse ?',
    false,
    ARRAY['Mandats simples mais peu d’exclusivités']::text[]
  ),
  (
    'conseiller-admin-synth-tiser-compromis-pr-sentation-vid-o-ou-vocale',
    'Synthétiser compromis (présentation vidéo ou vocale)',
    'Admin',
    'Conseiller',
    'conseiller',
    2.0,
    2.0,
    null,
    null,
    'Notebook',
    'Les compromis sont-ils expliqués de façon claire avant signature ? Les clients comprennent-ils les conditions, délais et engagements ? Le besoin est-il pédagogie, synthèse, vidéo de présentation ou sécurisation du parcours client ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-admin-automatisation-boite-mail',
    'Automatisation Boite mail',
    'Admin',
    'Conseiller',
    'conseiller',
    2.0,
    3.0,
    null,
    null,
    null,
    'La boîte mail ralentit-elle le traitement des demandes clients, notaires, diagnostiqueurs et vendeurs ? Quels délais de réponse constatez-vous ? Le besoin est-il tri, priorisation, modèles de réponse ou automatisation contrôlée ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-admin-veille-automatique-immo',
    'Veille automatique immo',
    'Admin',
    'Conseiller',
    'conseiller',
    1.0,
    3.0,
    null,
    null,
    null,
    'L''équipe suit-elle les évolutions marché, réglementaires et concurrentielles utiles au terrain ? Cette veille améliore-t-elle les estimations, relances vendeurs ou négociations ? Le besoin est-il source fiable, fréquence ou restitution simple ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-admin-my-juridic-assistant',
    'My juridic assistant',
    'Admin',
    'Conseiller',
    'conseiller',
    1.0,
    1.0,
    null,
    null,
    null,
    'Les conseillers savent-ils répondre aux questions juridiques simples sans improviser dangereusement ? Quels sujets reviennent : mandat, offre, DPE, copropriété, compromis ? Le besoin est-il réflexe de prudence, base documentaire ou assistant d''aide ?',
    false,
    ARRAY[]::text[]
  ),
  (
    'conseiller-admin-nursing-bdd',
    'Nursing BDD',
    'Admin',
    'Conseiller',
    'conseiller',
    2.0,
    4.0,
    null,
    null,
    null,
    'La base de données produit-elle des opportunités ou dort-elle paisiblement comme un fichier Excel abandonné ? Quels ratios suivez-vous : contacts relancés, réponses, RDV, mandats, visites ? Le besoin est-il segmentation, routine ou relance automatisée ?',
    false,
    ARRAY['Base acquéreurs ou vendeurs dormante', 'Organisation — CRM incomplet, relances oubliées, activité non pilotée']::text[]
  ),
  (
    'manager-base-param-trages-fonctionnalit-s-chat-gpt',
    'Chat gpt',
    'Base (paramétrages fonctionnalités)',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Équipe junior', 'Compétence — Écarts forts entre conseillers ou dépendance au manager', 'IA utile — IA utilisée sans indicateur de gain ou sans adoption terrain', 'Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'ChatGPT - paramétrage — Chaque conseiller utilise l''outil différemment ; résultats inégaux ; peur de l''erreur ou de la confidentialité.']::text[]
  ),
  (
    'manager-base-param-trages-fonctionnalit-s-gamma',
    'Gamma',
    'Base (paramétrages fonctionnalités)',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'Supports commerciaux faibles — Les conseillers savent-ils produire une présentation propre et orientée décision ?', 'Gamma — Supports moches, trop longs, faits à la dernière minute. Grande tradition locale.']::text[]
  ),
  (
    'manager-base-param-trages-fonctionnalit-s-notebook-lm',
    'Notebook LM',
    'Base (paramétrages fonctionnalités)',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Documents mal exploités — NotebookLM ou autre outil documentaire est-il connu et maîtrisé ?', 'NotebookLM — Lecture longue, erreurs d''interprétation, dépendance au manager pour synthétiser.']::text[]
  ),
  (
    'manager-base-param-trages-fonctionnalit-s-claude',
    'Claude',
    'Base (paramétrages fonctionnalités)',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'Claude — Documents hétérogènes, trames inexistantes, qualité dépendante de la personne.']::text[]
  ),
  (
    'manager-base-param-trages-fonctionnalit-s-gemini',
    'Gemini',
    'Base (paramétrages fonctionnalités)',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Gemini / Google Workspace — Infos dispersées, doublons, documents introuvables, relances oubliées.']::text[]
  ),
  (
    'manager-usecases-etude-de-march-biens-vendus',
    'Etude de marché biens vendus',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-etude-de-march-biens-la-vente',
    'Etude de marché biens à la vente',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-etude-de-march-agence',
    'Etude de marché agence',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-e-r-putation',
    'e réputation',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-training',
    'Training',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY['Équipe confirmée mais irrégulière']::text[]
  ),
  (
    'manager-usecases-pr-pa-r-union',
    'Prépa réunion',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-pr-pa-coaching',
    'Prépa coaching',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-agent-de-coaching',
    'Agent de coaching',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-automatisation-boite-mail',
    'Automatisation boite mail',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-veille-immo',
    'Veille immo',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-my-juridic-assistant',
    'My juridic assistant',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-assitant-recrutement',
    'Assitant recrutement',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-g-n-rateur-annonces-joab-board',
    'Générateur annonces joab board',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY['Beaucoup de vues mais peu de contacts', 'Diffusion — Beaucoup de vues mais peu de clics : annonce/photos. Beaucoup de visites mais peu d’offres : prix ou qualification']::text[]
  ),
  (
    'manager-usecases-analyse-cv',
    'Analyse CV',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'manager-usecases-suivi-recrutement',
    'Suivi recrutement',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY['Vendeurs difficiles à faire baisser', 'Suivi vendeur — Suivi irrégulier, vendeur surpris, baisses tardives']::text[]
  ),
  (
    'manager-usecases-onboarding-collab',
    'Onboarding collab',
    'Usecases',
    'Manager',
    'manager',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'assistant-base-param-trages-fonctionnalit-s-chat-gpt',
    'Chat gpt',
    'Base (paramétrages fonctionnalités)',
    'Assistantes',
    'assistant',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Équipe junior', 'Compétence — Écarts forts entre conseillers ou dépendance au manager', 'IA utile — IA utilisée sans indicateur de gain ou sans adoption terrain', 'Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'ChatGPT - paramétrage — Chaque conseiller utilise l''outil différemment ; résultats inégaux ; peur de l''erreur ou de la confidentialité.']::text[]
  ),
  (
    'assistant-base-param-trages-fonctionnalit-s-gamma',
    'Gamma',
    'Base (paramétrages fonctionnalités)',
    'Assistantes',
    'assistant',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'Supports commerciaux faibles — Les conseillers savent-ils produire une présentation propre et orientée décision ?', 'Gamma — Supports moches, trop longs, faits à la dernière minute. Grande tradition locale.']::text[]
  ),
  (
    'assistant-base-param-trages-fonctionnalit-s-notebook-lm',
    'Notebook LM',
    'Base (paramétrages fonctionnalités)',
    'Assistantes',
    'assistant',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Documents mal exploités — NotebookLM ou autre outil documentaire est-il connu et maîtrisé ?', 'NotebookLM — Lecture longue, erreurs d''interprétation, dépendance au manager pour synthétiser.']::text[]
  ),
  (
    'assistant-base-param-trages-fonctionnalit-s-claude',
    'Claude',
    'Base (paramétrages fonctionnalités)',
    'Assistantes',
    'assistant',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Socle IA non paramétré — Les outils sont-ils paramétrés, personnalisés et utilisés avec des modèles communs ?', 'Claude — Documents hétérogènes, trames inexistantes, qualité dépendante de la personne.']::text[]
  ),
  (
    'assistant-base-param-trages-fonctionnalit-s-gemini',
    'Gemini',
    'Base (paramétrages fonctionnalités)',
    'Assistantes',
    'assistant',
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    ARRAY['Gemini / Google Workspace — Infos dispersées, doublons, documents introuvables, relances oubliées.']::text[]
  ),
  (
    'assistant-prospection-usecases-etude-de-march-biens-vendus',
    'Etude de marché biens vendus',
    'Prospection (usecases)',
    'Assistantes',
    'assistant',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'assistant-prospection-usecases-etude-de-march-biens-la-vente',
    'Etude de marché biens à la vente',
    'Prospection (usecases)',
    'Assistantes',
    'assistant',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'assistant-prospection-usecases-etude-de-march-agence',
    'Etude de marché agence',
    'Prospection (usecases)',
    'Assistantes',
    'assistant',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  ),
  (
    'assistant-prospection-usecases-e-r-putation',
    'e réputation',
    'Prospection (usecases)',
    'Assistantes',
    'assistant',
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    ARRAY[]::text[]
  )
on conflict (id) do update set
  name = excluded.name,
  family = excluded.family,
  source_sheet = excluded.source_sheet,
  target_profile = excluded.target_profile,
  duration_hours = excluded.duration_hours,
  level = excluded.level,
  tools = excluded.tools,
  paying = excluded.paying,
  platform = excluded.platform,
  need_identification = excluded.need_identification,
  is_foundation_module = excluded.is_foundation_module,
  diagnostic_signals = excluded.diagnostic_signals;
